"""add referral models

Revision ID: 2026_08_28_102128
Revises: b2f972e1a29e
Create Date: 2026-08-28 10:21:28.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '2026_08_28_102128'
down_revision: Union[str, None] = 'b2f972e1a29e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('referraloffer',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('referrer_id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('weekly_capacity', sa.Integer(), nullable=False),
    sa.Column('current_week_count', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['referrer_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_referraloffer_company_id'), 'referraloffer', ['company_id'], unique=False)
    op.create_index(op.f('ix_referraloffer_referrer_id'), 'referraloffer', ['referrer_id'], unique=False)

    op.create_table('referralrequest',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('offer_id', sa.Uuid(), nullable=False),
    sa.Column('requester_id', sa.Uuid(), nullable=False),
    sa.Column('posting_id', sa.Uuid(), nullable=True),
    sa.Column('match_score', sa.Float(), nullable=True),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['offer_id'], ['referraloffer.id'], ),
    sa.ForeignKeyConstraint(['posting_id'], ['jobposting.id'], ),
    sa.ForeignKeyConstraint(['requester_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_referralrequest_offer_id'), 'referralrequest', ['offer_id'], unique=False)
    op.create_index(op.f('ix_referralrequest_requester_id'), 'referralrequest', ['requester_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_referralrequest_requester_id'), table_name='referralrequest')
    op.drop_index(op.f('ix_referralrequest_offer_id'), table_name='referralrequest')
    op.drop_table('referralrequest')
    
    op.drop_index(op.f('ix_referraloffer_referrer_id'), table_name='referraloffer')
    op.drop_index(op.f('ix_referraloffer_company_id'), table_name='referraloffer')
    op.drop_table('referraloffer')
    # ### end Alembic commands ###

