"""update referral and job models

Revision ID: 92481d7c5087
Revises: 2026_08_28_102128
Create Date: 2026-08-28 14:36:16.842237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '92481d7c5087'
down_revision: Union[str, Sequence[str], None] = '2026_08_28_102128'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('application', sa.Column('resume_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('application', sa.Column('referred_by_id', sa.Uuid(), nullable=True))
    op.add_column('application', sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_foreign_key(None, 'application', 'user', ['referred_by_id'], ['id'])
    op.add_column('jobposting', sa.Column('response_timeframe_days', sa.Integer(), nullable=False))
    op.add_column('jobposting', sa.Column('referral_limit', sa.Integer(), nullable=False))
    op.add_column('referraloffer', sa.Column('posting_id', sa.Uuid(), nullable=False))
    op.add_column('referraloffer', sa.Column('accepted_count', sa.Integer(), nullable=False))
    op.add_column('jobposting', sa.Column('response_timeframe_days', sa.Integer(), nullable=False, server_default='30'))
    op.add_column('jobposting', sa.Column('referral_limit', sa.Integer(), nullable=False, server_default='5'))
    op.add_column('referraloffer', sa.Column('posting_id', sa.Uuid(), nullable=False, server_default='00000000-0000-0000-0000-000000000000'))
    op.add_column('referraloffer', sa.Column('accepted_count', sa.Integer(), nullable=False, server_default='0'))
    op.create_index(op.f('ix_referraloffer_posting_id'), 'referraloffer', ['posting_id'], unique=False)
    op.create_foreign_key(None, 'referraloffer', 'jobposting', ['posting_id'], ['id'])
    op.drop_column('referraloffer', 'current_week_count')
    op.drop_column('referraloffer', 'weekly_capacity')
    op.add_column('referralrequest', sa.Column('resume_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.alter_column('referralrequest', 'posting_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.create_index(op.f('ix_referralrequest_posting_id'), 'referralrequest', ['posting_id'], unique=False)
    op.add_column('user', sa.Column('employer_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_user_employer_id'), 'user', ['employer_id'], unique=False)
    op.create_foreign_key(None, 'user', 'company', ['employer_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_index(op.f('ix_user_employer_id'), table_name='user')
    op.drop_column('user', 'employer_id')
    op.drop_index(op.f('ix_referralrequest_posting_id'), table_name='referralrequest')
    op.alter_column('referralrequest', 'posting_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('referralrequest', 'resume_url')
    op.add_column('referraloffer', sa.Column('weekly_capacity', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('referraloffer', sa.Column('current_week_count', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'referraloffer', type_='foreignkey')
    op.drop_index(op.f('ix_referraloffer_posting_id'), table_name='referraloffer')
    op.drop_column('referraloffer', 'accepted_count')
    op.drop_column('referraloffer', 'posting_id')
    op.drop_column('jobposting', 'referral_limit')
    op.drop_column('jobposting', 'response_timeframe_days')
    op.drop_constraint(None, 'application', type_='foreignkey')
    op.drop_column('application', 'notes')
    op.drop_column('application', 'referred_by_id')
    op.drop_column('application', 'resume_url')
    # ### end Alembic commands ###
