"""Initial data models

Revision ID: b2f972e1a29e
Revises: 
Create Date: 2026-08-16 19:09:32.996024

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b2f972e1a29e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('website', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('median_response_hours', sa.Float(), nullable=True),
    sa.Column('ghosting_rate', sa.Float(), nullable=True),
    sa.Column('interview_to_offer_rate', sa.Float(), nullable=True),
    sa.Column('total_tracked_applications', sa.Integer(), nullable=False),
    sa.Column('score_last_computed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_name'), 'company', ['name'], unique=False)
    op.create_index(op.f('ix_company_slug'), 'company', ['slug'], unique=True)
    op.create_table('user',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role', sa.Enum('CANDIDATE', 'RECRUITER', 'BOTH', name='userrole'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('communitythread',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('entity_type', sa.Enum('COMPANY', 'POSTING', name='entitytype'), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('author_id', sa.Uuid(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_community_thread_entity', 'communitythread', ['entity_type', 'entity_id'], unique=False)
    op.create_index(op.f('ix_communitythread_entity_id'), 'communitythread', ['entity_id'], unique=False)
    op.create_table('jobposting',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('posted_by_user_id', sa.Uuid(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('requirements', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('location', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_remote', sa.Boolean(), nullable=False),
    sa.Column('salary_min', sa.Integer(), nullable=True),
    sa.Column('salary_max', sa.Integer(), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'CLOSED', 'FLAGGED_SUSPICIOUS', name='postingstatus'), nullable=False),
    sa.Column('scam_risk_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['posted_by_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_job_posting_company_id_status', 'jobposting', ['company_id', 'status'], unique=False)
    op.create_index(op.f('ix_jobposting_company_id'), 'jobposting', ['company_id'], unique=False)
    op.create_table('notification',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_user_id'), 'notification', ['user_id'], unique=False)
    op.create_table('profile',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('headline', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('bio', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('skills', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('resume_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('location', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profile_user_id'), 'profile', ['user_id'], unique=True)
    op.create_table('application',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('posting_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('APPLIED', 'VIEWED', 'SCREENING', 'INTERVIEW', 'OFFER', 'REJECTED', 'GHOSTED', 'WITHDRAWN', name='applicationstatus'), nullable=False),
    sa.Column('status_history', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('cover_note', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('applied_at', sa.DateTime(), nullable=False),
    sa.Column('last_employer_response_at', sa.DateTime(), nullable=True),
    sa.Column('is_ghosted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['posting_id'], ['jobposting.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'posting_id', name='uq_user_posting_application')
    )
    op.create_index(op.f('ix_application_posting_id'), 'application', ['posting_id'], unique=False)
    op.create_index('ix_application_posting_id_status', 'application', ['posting_id', 'status'], unique=False)
    op.create_index(op.f('ix_application_user_id'), 'application', ['user_id'], unique=False)
    op.create_table('communitypost',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('thread_id', sa.Uuid(), nullable=False),
    sa.Column('author_id', sa.Uuid(), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['thread_id'], ['communitythread.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_communitypost_thread_id'), 'communitypost', ['thread_id'], unique=False)
    op.create_table('prepbriefcache',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('posting_id', sa.Uuid(), nullable=False),
    sa.Column('summary_markdown', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_intel_count', sa.Integer(), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['posting_id'], ['jobposting.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prepbriefcache_posting_id'), 'prepbriefcache', ['posting_id'], unique=True)
    op.create_table('interviewintel',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('author_id', sa.Uuid(), nullable=False),
    sa.Column('posting_id', sa.Uuid(), nullable=False),
    sa.Column('company_id', sa.Uuid(), nullable=False),
    sa.Column('verified_via_application_id', sa.Uuid(), nullable=False),
    sa.Column('rounds', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('overall_difficulty', sa.Integer(), nullable=True),
    sa.Column('outcome', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_anonymous', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['posting_id'], ['jobposting.id'], ),
    sa.ForeignKeyConstraint(['verified_via_application_id'], ['application.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interviewintel_company_id'), 'interviewintel', ['company_id'], unique=False)
    op.create_index(op.f('ix_interviewintel_posting_id'), 'interviewintel', ['posting_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_interviewintel_posting_id'), table_name='interviewintel')
    op.drop_index(op.f('ix_interviewintel_company_id'), table_name='interviewintel')
    op.drop_table('interviewintel')
    op.drop_index(op.f('ix_prepbriefcache_posting_id'), table_name='prepbriefcache')
    op.drop_table('prepbriefcache')
    op.drop_index(op.f('ix_communitypost_thread_id'), table_name='communitypost')
    op.drop_table('communitypost')
    op.drop_index(op.f('ix_application_user_id'), table_name='application')
    op.drop_index('ix_application_posting_id_status', table_name='application')
    op.drop_index(op.f('ix_application_posting_id'), table_name='application')
    op.drop_table('application')
    op.drop_index(op.f('ix_profile_user_id'), table_name='profile')
    op.drop_table('profile')
    op.drop_index(op.f('ix_notification_user_id'), table_name='notification')
    op.drop_table('notification')
    op.drop_index(op.f('ix_jobposting_company_id'), table_name='jobposting')
    op.drop_index('ix_job_posting_company_id_status', table_name='jobposting')
    op.drop_table('jobposting')
    op.drop_index(op.f('ix_communitythread_entity_id'), table_name='communitythread')
    op.drop_index('ix_community_thread_entity', table_name='communitythread')
    op.drop_table('communitythread')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_company_slug'), table_name='company')
    op.drop_index(op.f('ix_company_name'), table_name='company')
    op.drop_table('company')
    # ### end Alembic commands ###
